improve tmux status bar and bash prompt - add git status to status bar (and remove it from bash prompt) - get better cpu/mem monitor - print non-zero exit status before bash prompt

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -5,11 +5,6 @@
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
-# start tmux by default
-if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
-    tmux attach -t default || tmux new -s default
-fi
-
 ################################################################################
 # PATH
 ################################################################################
@@ -30,14 +25,16 @@ export PATH
 # BASH SETTINGS
 ################################################################################
 
-if [ -f "$HOME/dotfiles/shell/use-git-prompt.bash" ]; then
-    # set prompt to "[<current directory>:<git status>]$ "
-    . "$HOME/dotfiles/shell/use-git-prompt.bash"
-else
-    # set prompt to "[<current directory>]$ "
-    PS1="[\[\e[36m\]\W\[\e[m\]]\\$ "
-fi
+__prompt() {
+    local EXIT="$?"
+    PS1=""
+    if [ "$EXIT" != 0 ]; then
+        PS1="\[\e[31;1m\]exit $EXIT\[\e[m\]\n" # "exit <exit status>"
+    fi
+    PS1="$PS1[\[\e[36m\]\w\[\e[m\]]\\$ " # "[<current directory>]$ "
+}
 
+PROMPT_COMMAND=__prompt
 set -o vi                           # use vi mode
 export HISTSIZE=                    # unlimited history
 export HISTFILESIZE=                # unlimited history file
@@ -116,4 +113,10 @@ export RIPGREP_CONFIG_PATH="$HOME/dotfiles/ripgreprc" # set ripgrep config file
 
 # source an extra file that isn't tracked by dotfiles repo for local-only configs
 [[ -f ~/.bash_extra ]] && . ~/.bash_extra
+
+# start tmux by default - needs to be last for settings set here to apply to
+# tmux server
+if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
+   tmux attach -t default || tmux new -s default
+fi
 
